"""
Regenerate the auto-generated sections of ``docs/opentrons.md``.

Currently regenerates one block:

- **Duration model reference table** — every entry of
  :data:`opentrons.duration_model.DURATION_SECONDS`, in a markdown
  table, between marker comments. The Python dict is the single
  source of truth; this script keeps the markdown in sync so a
  contributor never needs to edit the table by hand.

Usage::

    python -m rhylthyme_importers.opentrons.docs_gen        # rewrite docs in-place
    python -m rhylthyme_importers.opentrons.docs_gen --check  # exit non-zero if regenerated docs differ

Wire ``--check`` into CI to catch drift before it ships.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

from .duration_model import DURATION_SECONDS

DOCS_PATH = (
    Path(__file__).resolve().parent.parent.parent.parent
    / 'docs' / 'opentrons.md'
)

_START_MARKER = '<!-- BEGIN AUTOGENERATED: duration-model -->'
_END_MARKER = '<!-- END AUTOGENERATED: duration-model -->'


# Human-readable hints per command_type. Kept here (not in the live
# duration_model module) so the runtime stays lean. Missing entries
# fall back to an empty cell.
_NOTES: dict[str, str] = {
    'pickup_tip': 'Tip pickup (any pipette).',
    'drop_tip': 'Drop tip into trash.',
    'aspirate': 'Single-well aspirate; ignores volume in the static model.',
    'dispense': 'Single-well dispense.',
    'air_gap': 'Pull a small air buffer into the tip.',
    'blow_out': 'Force remaining liquid out of the tip.',
    'mix': 'Per repetition; total = base × ``repetitions``.',
    'touch_tip': 'Brush the tip against the well rim.',
    'move_to': 'Move the pipette to a named location.',
    'home': 'Send pipette / gantry to home.',
    'transfer': 'Helper-method fallback (AST path only).',
    'distribute': 'Helper-method fallback (AST path only).',
    'consolidate': 'Helper-method fallback (AST path only).',
    'delay': 'Reads ``event.args["seconds"]`` from the protocol.',
    'pause': 'Renders as indefinite duration / manual trigger.',
    'heater_shaker.shake': 'Default placeholder; protocols typically gate shake duration with a follow-up call.',
    'heater_shaker.set_target_temperature': '',
    'heater_shaker.wait_for_temperature': '',
    'heater_shaker.deactivate_shaker': '',
    'heater_shaker.deactivate_heater': '',
    'heater_shaker.open_labware_latch': '',
    'heater_shaker.close_labware_latch': '',
    'magnetic.engage': 'Settle-time estimate; tune for your bead chemistry.',
    'magnetic.disengage': '',
    'temperature.set_temperature': '',
    'temperature.await_temperature': 'Block-warm-up estimate; varies by setpoint.',
    'temperature.deactivate': '',
    'thermocycler.open_lid': '',
    'thermocycler.close_lid': '',
    'thermocycler.set_block_temperature': '',
    'thermocycler.set_lid_temperature': '',
    'thermocycler.execute_profile': 'Computed at parse time: ``sum(step.hold_time_seconds) * repetitions``.',
    'thermocycler.deactivate': '',
    'absorbance.initialize': '',
    'absorbance.read': '',
    'absorbance.open_lid': '',
    'absorbance.close_lid': '',
    'gripper.move_labware': 'One labware traverse on the Flex deck.',
}


def _render_table() -> str:
    """Build the markdown table from ``DURATION_SECONDS``."""
    lines = [
        '| Command type | Seconds | Notes |',
        '|---|---:|---|',
    ]
    for ct in sorted(DURATION_SECONDS.keys()):
        secs = DURATION_SECONDS[ct]
        note = _NOTES.get(ct, '')
        lines.append(f'| `{ct}` | {secs} | {note} |')
    return '\n'.join(lines)


def _splice(existing: str, replacement: str) -> str:
    """Replace the content between the markers with ``replacement``.

    Adds the markers + replacement at the end of the file if they're
    missing, so first-run wiring doesn't need a separate command.
    """
    block = f'{_START_MARKER}\n\n{replacement}\n\n{_END_MARKER}'
    if _START_MARKER not in existing or _END_MARKER not in existing:
        # Append at the bottom under a fresh heading.
        appendix = (
            f'\n\n## Duration model reference (auto-generated)\n\n'
            f'_Regenerate with `make docs` after editing `DURATION_SECONDS` in '
            f'`opentrons/duration_model.py`._\n\n{block}\n'
        )
        return existing.rstrip() + appendix
    pattern = re.compile(
        re.escape(_START_MARKER) + r'.*?' + re.escape(_END_MARKER),
        re.DOTALL,
    )
    return pattern.sub(block, existing, count=1)


def run(check_only: bool = False) -> int:
    docs = DOCS_PATH
    if not docs.exists():
        sys.stderr.write(f'error: docs file not found: {docs}\n')
        return 2
    existing = docs.read_text(encoding='utf-8')
    regen = _splice(existing, _render_table())
    if check_only:
        if regen == existing:
            print('docs are up to date.')
            return 0
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            regen.splitlines(keepends=True),
            fromfile='docs/opentrons.md (current)',
            tofile='docs/opentrons.md (regenerated)',
            n=2,
        )
        sys.stderr.write('docs are out of date. Run `make docs` and commit the result.\n')
        sys.stderr.writelines(diff)
        return 1
    docs.write_text(regen, encoding='utf-8')
    print(f'wrote {docs}')
    return 0


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true',
                   help='exit non-zero if docs are out of date (CI mode)')
    args = p.parse_args()
    sys.exit(run(check_only=args.check))


if __name__ == '__main__':
    main()
